### ISSUE TITLE
can't set 'none' to samesite

### ISSUE THREAD

**Issue by tyiss** [cloudflare/lua-resty-cookie#31]
The code is limiting the possible values of samesite attribute to either 'Strict' or 'Lax'.
however there is another possible value: *none*.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies

**Comment by eberbis** [comment]
Following up @tyiss comment, I came across the same issue. 
Anything different than `Strict` or `Lax` is currently considered as invalid. I have implemented a change to allow for `None`. 

@p0pr0ck5, would you or any contributor have some time to review it? https://github.com/cloudflare/lua-resty-cookie/pull/32

Thanks in advance

**Comment by jdesgats** [comment]
I just merged the PR #32 mentioned by @eberbisl. This issue should be fixed now.
