### ISSUE TITLE
have a extra comma (,) in what I get using cookie:get("xxx")

### ISSUE THREAD

**Issue by hy05190134** [cloudflare/lua-resty-cookie#6]
cookie = ck:new()
cookie:set({key = "aa", value = "vaa"})
cookie:set({key = "bb", value = "vbb"})

next time I using the cookie to using cookie:get("aa"), it return "vaa,",  not just "vaa"

**Comment by calio** [comment]
It looks like there is a bit confusion here. `set` is used to set cookie to client, so it only affects response header. `get` is used to get cookies that client sends to server. So if you use `cookie:set` and `cookie:get` in the same request, `cookie:get` will return the client cookie. Not the one you just set.

**Comment by hy05190134** [comment]
finally, it is my default that in my case headers["Cookie"] = "xxx, xxx, xx" but not "xxx; xxx; xx", thank you for replying my questions.
